python goexplore.py --seed=0 --env_id=Alien            --h=16 --w=19 --d=9  --max_cells=50000 --save_archive=./data/gesweep/Alien_0.npy            &
python goexplore.py --seed=0 --env_id=Amidar           --h=4  --w=7  --d=15 --max_cells=50000 --save_archive=./data/gesweep/Amidar_0.npy           &
python goexplore.py --seed=0 --env_id=Assault          --h=7  --w=11 --d=13 --max_cells=50000 --save_archive=./data/gesweep/Assault_0.npy          &
python goexplore.py --seed=0 --env_id=Asterix          --h=7  --w=9  --d=6  --max_cells=50000 --save_archive=./data/gesweep/Asterix_0.npy          &
python goexplore.py --seed=0 --env_id=Asteroids        --h=8  --w=11 --d=10 --max_cells=50000 --save_archive=./data/gesweep/Asteroids_0.npy        &
python goexplore.py --seed=0 --env_id=Atlantis         --h=12 --w=12 --d=16 --max_cells=50000 --save_archive=./data/gesweep/Atlantis_0.npy         &
python goexplore.py --seed=0 --env_id=BankHeist        --h=14 --w=5  --d=10 --max_cells=50000 --save_archive=./data/gesweep/BankHeist_0.npy        &
python goexplore.py --seed=0 --env_id=BattleZone       --h=11 --w=11 --d=18 --max_cells=50000 --save_archive=./data/gesweep/BattleZone_0.npy       &
python goexplore.py --seed=0 --env_id=BeamRider        --h=12 --w=5  --d=9  --max_cells=50000 --save_archive=./data/gesweep/BeamRider_0.npy        &
python goexplore.py --seed=0 --env_id=Berzerk          --h=13 --w=17 --d=12 --max_cells=50000 --save_archive=./data/gesweep/Berzerk_0.npy          &
python goexplore.py --seed=0 --env_id=Bowling          --h=13 --w=8  --d=7  --max_cells=50000 --save_archive=./data/gesweep/Bowling_0.npy          &
python goexplore.py --seed=0 --env_id=Boxing           --h=4  --w=7  --d=9  --max_cells=50000 --save_archive=./data/gesweep/Boxing_0.npy           &
python goexplore.py --seed=0 --env_id=Breakout         --h=18 --w=19 --d=19 --max_cells=50000 --save_archive=./data/gesweep/Breakout_0.npy         &
python goexplore.py --seed=0 --env_id=Centipede        --h=4  --w=6  --d=7  --max_cells=50000 --save_archive=./data/gesweep/Centipede_0.npy        &
python goexplore.py --seed=0 --env_id=ChopperCommand   --h=12 --w=5  --d=7  --max_cells=50000 --save_archive=./data/gesweep/ChopperCommand_0.npy   &
python goexplore.py --seed=0 --env_id=CrazyClimber     --h=17 --w=7  --d=7  --max_cells=50000 --save_archive=./data/gesweep/CrazyClimber_0.npy     &
python goexplore.py --seed=0 --env_id=Defender         --h=18 --w=11 --d=4  --max_cells=50000 --save_archive=./data/gesweep/Defender_0.npy         &
python goexplore.py --seed=0 --env_id=DemonAttack      --h=5  --w=13 --d=13 --max_cells=50000 --save_archive=./data/gesweep/DemonAttack_0.npy      &
python goexplore.py --seed=0 --env_id=DoubleDunk       --h=19 --w=4  --d=19 --max_cells=50000 --save_archive=./data/gesweep/DoubleDunk_0.npy       &
python goexplore.py --seed=0 --env_id=Enduro           --h=14 --w=8  --d=11 --max_cells=50000 --save_archive=./data/gesweep/Enduro_0.npy           &
python goexplore.py --seed=0 --env_id=FishingDerby     --h=7  --w=18 --d=15 --max_cells=50000 --save_archive=./data/gesweep/FishingDerby_0.npy     &
python goexplore.py --seed=0 --env_id=Freeway          --h=6  --w=11 --d=16 --max_cells=50000 --save_archive=./data/gesweep/Freeway_0.npy          &
python goexplore.py --seed=0 --env_id=Frostbite        --h=6  --w=4  --d=4  --max_cells=50000 --save_archive=./data/gesweep/Frostbite_0.npy        &
python goexplore.py --seed=0 --env_id=Gopher           --h=8  --w=9  --d=9  --max_cells=50000 --save_archive=./data/gesweep/Gopher_0.npy           &
python goexplore.py --seed=0 --env_id=Gravitar         --h=10 --w=12 --d=8  --max_cells=50000 --save_archive=./data/gesweep/Gravitar_0.npy         &
python goexplore.py --seed=0 --env_id=Hero             --h=5  --w=19 --d=8  --max_cells=50000 --save_archive=./data/gesweep/Hero_0.npy             &
python goexplore.py --seed=0 --env_id=IceHockey        --h=13 --w=14 --d=14 --max_cells=50000 --save_archive=./data/gesweep/IceHockey_0.npy        &
python goexplore.py --seed=0 --env_id=Jamesbond        --h=19 --w=12 --d=5  --max_cells=50000 --save_archive=./data/gesweep/Jamesbond_0.npy        &
python goexplore.py --seed=0 --env_id=Kangaroo         --h=5  --w=11 --d=13 --max_cells=50000 --save_archive=./data/gesweep/Kangaroo_0.npy         &
python goexplore.py --seed=0 --env_id=Krull            --h=13 --w=7  --d=10 --max_cells=50000 --save_archive=./data/gesweep/Krull_0.npy            &
python goexplore.py --seed=0 --env_id=KungFuMaster     --h=11 --w=15 --d=18 --max_cells=50000 --save_archive=./data/gesweep/KungFuMaster_0.npy     &
python goexplore.py --seed=0 --env_id=MontezumaRevenge --h=6  --w=15 --d=4  --max_cells=50000 --save_archive=./data/gesweep/MontezumaRevenge_0.npy &
python goexplore.py --seed=0 --env_id=MsPacman         --h=18 --w=7  --d=9  --max_cells=50000 --save_archive=./data/gesweep/MsPacman_0.npy         &
python goexplore.py --seed=0 --env_id=NameThisGame     --h=16 --w=13 --d=14 --max_cells=50000 --save_archive=./data/gesweep/NameThisGame_0.npy     &
python goexplore.py --seed=0 --env_id=Phoenix          --h=8  --w=15 --d=8  --max_cells=50000 --save_archive=./data/gesweep/Phoenix_0.npy          &
python goexplore.py --seed=0 --env_id=Pitfall          --h=10 --w=8  --d=19 --max_cells=50000 --save_archive=./data/gesweep/Pitfall_0.npy          &
python goexplore.py --seed=0 --env_id=Pong             --h=19 --w=8  --d=7  --max_cells=50000 --save_archive=./data/gesweep/Pong_0.npy             &
python goexplore.py --seed=0 --env_id=PrivateEye       --h=16 --w=8  --d=8  --max_cells=50000 --save_archive=./data/gesweep/PrivateEye_0.npy       &
python goexplore.py --seed=0 --env_id=Qbert            --h=12 --w=18 --d=19 --max_cells=50000 --save_archive=./data/gesweep/Qbert_0.npy            &
python goexplore.py --seed=0 --env_id=Riverraid        --h=8  --w=7  --d=14 --max_cells=50000 --save_archive=./data/gesweep/Riverraid_0.npy        &
wait

python goexplore.py --seed=1 --env_id=Alien            --h=11 --w=19 --d=17 --max_cells=50000 --save_archive=./data/gesweep/Alien_1.npy            &
python goexplore.py --seed=1 --env_id=Amidar           --h=9  --w=9  --d=4  --max_cells=50000 --save_archive=./data/gesweep/Amidar_1.npy           &
python goexplore.py --seed=1 --env_id=Assault          --h=5  --w=9  --d=13 --max_cells=50000 --save_archive=./data/gesweep/Assault_1.npy          &
python goexplore.py --seed=1 --env_id=Asterix          --h=7  --w=4  --d=19 --max_cells=50000 --save_archive=./data/gesweep/Asterix_1.npy          &
python goexplore.py --seed=1 --env_id=Asteroids        --h=9  --w=18 --d=4  --max_cells=50000 --save_archive=./data/gesweep/Asteroids_1.npy        &
python goexplore.py --seed=1 --env_id=Atlantis         --h=5  --w=6  --d=8  --max_cells=50000 --save_archive=./data/gesweep/Atlantis_1.npy         &
python goexplore.py --seed=1 --env_id=BankHeist        --h=6  --w=4  --d=17 --max_cells=50000 --save_archive=./data/gesweep/BankHeist_1.npy        &
python goexplore.py --seed=1 --env_id=BattleZone       --h=7  --w=6  --d=14 --max_cells=50000 --save_archive=./data/gesweep/BattleZone_1.npy       &
python goexplore.py --seed=1 --env_id=BeamRider        --h=17 --w=4  --d=11 --max_cells=50000 --save_archive=./data/gesweep/BeamRider_1.npy        &
python goexplore.py --seed=1 --env_id=Berzerk          --h=9  --w=13 --d=19 --max_cells=50000 --save_archive=./data/gesweep/Berzerk_1.npy          &
python goexplore.py --seed=1 --env_id=Bowling          --h=4  --w=14 --d=6  --max_cells=50000 --save_archive=./data/gesweep/Bowling_1.npy          &
python goexplore.py --seed=1 --env_id=Boxing           --h=15 --w=14 --d=19 --max_cells=50000 --save_archive=./data/gesweep/Boxing_1.npy           &
python goexplore.py --seed=1 --env_id=Breakout         --h=11 --w=15 --d=6  --max_cells=50000 --save_archive=./data/gesweep/Breakout_1.npy         &
python goexplore.py --seed=1 --env_id=Centipede        --h=13 --w=6  --d=18 --max_cells=50000 --save_archive=./data/gesweep/Centipede_1.npy        &
python goexplore.py --seed=1 --env_id=ChopperCommand   --h=7  --w=18 --d=15 --max_cells=50000 --save_archive=./data/gesweep/ChopperCommand_1.npy   &
python goexplore.py --seed=1 --env_id=CrazyClimber     --h=7  --w=6  --d=18 --max_cells=50000 --save_archive=./data/gesweep/CrazyClimber_1.npy     &
python goexplore.py --seed=1 --env_id=Defender         --h=7  --w=8  --d=5  --max_cells=50000 --save_archive=./data/gesweep/Defender_1.npy         &
python goexplore.py --seed=1 --env_id=DemonAttack      --h=6  --w=15 --d=18 --max_cells=50000 --save_archive=./data/gesweep/DemonAttack_1.npy      &
python goexplore.py --seed=1 --env_id=DoubleDunk       --h=13 --w=14 --d=5  --max_cells=50000 --save_archive=./data/gesweep/DoubleDunk_1.npy       &
python goexplore.py --seed=1 --env_id=Enduro           --h=8  --w=14 --d=10 --max_cells=50000 --save_archive=./data/gesweep/Enduro_1.npy           &
python goexplore.py --seed=1 --env_id=FishingDerby     --h=15 --w=12 --d=15 --max_cells=50000 --save_archive=./data/gesweep/FishingDerby_1.npy     &
python goexplore.py --seed=1 --env_id=Freeway          --h=6  --w=7  --d=4  --max_cells=50000 --save_archive=./data/gesweep/Freeway_1.npy          &
python goexplore.py --seed=1 --env_id=Frostbite        --h=4  --w=10 --d=4  --max_cells=50000 --save_archive=./data/gesweep/Frostbite_1.npy        &
python goexplore.py --seed=1 --env_id=Gopher           --h=10 --w=7  --d=18 --max_cells=50000 --save_archive=./data/gesweep/Gopher_1.npy           &
python goexplore.py --seed=1 --env_id=Gravitar         --h=14 --w=7  --d=12 --max_cells=50000 --save_archive=./data/gesweep/Gravitar_1.npy         &
python goexplore.py --seed=1 --env_id=Hero             --h=16 --w=12 --d=17 --max_cells=50000 --save_archive=./data/gesweep/Hero_1.npy             &
python goexplore.py --seed=1 --env_id=IceHockey        --h=18 --w=12 --d=17 --max_cells=50000 --save_archive=./data/gesweep/IceHockey_1.npy        &
python goexplore.py --seed=1 --env_id=Jamesbond        --h=6  --w=7  --d=18 --max_cells=50000 --save_archive=./data/gesweep/Jamesbond_1.npy        &
python goexplore.py --seed=1 --env_id=Kangaroo         --h=6  --w=15 --d=17 --max_cells=50000 --save_archive=./data/gesweep/Kangaroo_1.npy         &
python goexplore.py --seed=1 --env_id=Krull            --h=4  --w=12 --d=12 --max_cells=50000 --save_archive=./data/gesweep/Krull_1.npy            &
python goexplore.py --seed=1 --env_id=KungFuMaster     --h=7  --w=19 --d=12 --max_cells=50000 --save_archive=./data/gesweep/KungFuMaster_1.npy     &
python goexplore.py --seed=1 --env_id=MontezumaRevenge --h=14 --w=6  --d=12 --max_cells=50000 --save_archive=./data/gesweep/MontezumaRevenge_1.npy &
python goexplore.py --seed=1 --env_id=MsPacman         --h=8  --w=7  --d=16 --max_cells=50000 --save_archive=./data/gesweep/MsPacman_1.npy         &
python goexplore.py --seed=1 --env_id=NameThisGame     --h=17 --w=18 --d=4  --max_cells=50000 --save_archive=./data/gesweep/NameThisGame_1.npy     &
python goexplore.py --seed=1 --env_id=Phoenix          --h=8  --w=7  --d=17 --max_cells=50000 --save_archive=./data/gesweep/Phoenix_1.npy          &
python goexplore.py --seed=1 --env_id=Pitfall          --h=15 --w=16 --d=10 --max_cells=50000 --save_archive=./data/gesweep/Pitfall_1.npy          &
python goexplore.py --seed=1 --env_id=Pong             --h=17 --w=13 --d=17 --max_cells=50000 --save_archive=./data/gesweep/Pong_1.npy             &
python goexplore.py --seed=1 --env_id=PrivateEye       --h=15 --w=12 --d=4  --max_cells=50000 --save_archive=./data/gesweep/PrivateEye_1.npy       &
python goexplore.py --seed=1 --env_id=Qbert            --h=12 --w=17 --d=9  --max_cells=50000 --save_archive=./data/gesweep/Qbert_1.npy            &
python goexplore.py --seed=1 --env_id=Riverraid        --h=18 --w=13 --d=4  --max_cells=50000 --save_archive=./data/gesweep/Riverraid_1.npy        &
wait

python goexplore.py --seed=2 --env_id=Alien            --h=16 --w=13 --d=10 --max_cells=50000 --save_archive=./data/gesweep/Alien_2.npy            &
python goexplore.py --seed=2 --env_id=Amidar           --h=9  --w=17 --d=7  --max_cells=50000 --save_archive=./data/gesweep/Amidar_2.npy           &
python goexplore.py --seed=2 --env_id=Assault          --h=5  --w=12 --d=4  --max_cells=50000 --save_archive=./data/gesweep/Assault_2.npy          &
python goexplore.py --seed=2 --env_id=Asterix          --h=8  --w=15 --d=15 --max_cells=50000 --save_archive=./data/gesweep/Asterix_2.npy          &
python goexplore.py --seed=2 --env_id=Asteroids        --h=13 --w=10 --d=9  --max_cells=50000 --save_archive=./data/gesweep/Asteroids_2.npy        &
python goexplore.py --seed=2 --env_id=Atlantis         --h=19 --w=17 --d=11 --max_cells=50000 --save_archive=./data/gesweep/Atlantis_2.npy         &
python goexplore.py --seed=2 --env_id=BankHeist        --h=12 --w=12 --d=19 --max_cells=50000 --save_archive=./data/gesweep/BankHeist_2.npy        &
python goexplore.py --seed=2 --env_id=BattleZone       --h=13 --w=6  --d=12 --max_cells=50000 --save_archive=./data/gesweep/BattleZone_2.npy       &
python goexplore.py --seed=2 --env_id=BeamRider        --h=10 --w=19 --d=15 --max_cells=50000 --save_archive=./data/gesweep/BeamRider_2.npy        &
python goexplore.py --seed=2 --env_id=Berzerk          --h=10 --w=19 --d=17 --max_cells=50000 --save_archive=./data/gesweep/Berzerk_2.npy          &
python goexplore.py --seed=2 --env_id=Bowling          --h=13 --w=5  --d=19 --max_cells=50000 --save_archive=./data/gesweep/Bowling_2.npy          &
python goexplore.py --seed=2 --env_id=Boxing           --h=10 --w=16 --d=12 --max_cells=50000 --save_archive=./data/gesweep/Boxing_2.npy           &
python goexplore.py --seed=2 --env_id=Breakout         --h=17 --w=12 --d=7  --max_cells=50000 --save_archive=./data/gesweep/Breakout_2.npy         &
python goexplore.py --seed=2 --env_id=Centipede        --h=6  --w=19 --d=7  --max_cells=50000 --save_archive=./data/gesweep/Centipede_2.npy        &
python goexplore.py --seed=2 --env_id=ChopperCommand   --h=14 --w=16 --d=10 --max_cells=50000 --save_archive=./data/gesweep/ChopperCommand_2.npy   &
python goexplore.py --seed=2 --env_id=CrazyClimber     --h=7  --w=10 --d=18 --max_cells=50000 --save_archive=./data/gesweep/CrazyClimber_2.npy     &
python goexplore.py --seed=2 --env_id=Defender         --h=17 --w=9  --d=11 --max_cells=50000 --save_archive=./data/gesweep/Defender_2.npy         &
python goexplore.py --seed=2 --env_id=DemonAttack      --h=15 --w=4  --d=15 --max_cells=50000 --save_archive=./data/gesweep/DemonAttack_2.npy      &
python goexplore.py --seed=2 --env_id=DoubleDunk       --h=12 --w=8  --d=14 --max_cells=50000 --save_archive=./data/gesweep/DoubleDunk_2.npy       &
python goexplore.py --seed=2 --env_id=Enduro           --h=10 --w=15 --d=9  --max_cells=50000 --save_archive=./data/gesweep/Enduro_2.npy           &
python goexplore.py --seed=2 --env_id=FishingDerby     --h=17 --w=16 --d=19 --max_cells=50000 --save_archive=./data/gesweep/FishingDerby_2.npy     &
python goexplore.py --seed=2 --env_id=Freeway          --h=12 --w=6  --d=15 --max_cells=50000 --save_archive=./data/gesweep/Freeway_2.npy          &
python goexplore.py --seed=2 --env_id=Frostbite        --h=7  --w=13 --d=11 --max_cells=50000 --save_archive=./data/gesweep/Frostbite_2.npy        &
python goexplore.py --seed=2 --env_id=Gopher           --h=9  --w=7  --d=18 --max_cells=50000 --save_archive=./data/gesweep/Gopher_2.npy           &
python goexplore.py --seed=2 --env_id=Gravitar         --h=8  --w=9  --d=17 --max_cells=50000 --save_archive=./data/gesweep/Gravitar_2.npy         &
python goexplore.py --seed=2 --env_id=Hero             --h=7  --w=7  --d=11 --max_cells=50000 --save_archive=./data/gesweep/Hero_2.npy             &
python goexplore.py --seed=2 --env_id=IceHockey        --h=13 --w=13 --d=13 --max_cells=50000 --save_archive=./data/gesweep/IceHockey_2.npy        &
python goexplore.py --seed=2 --env_id=Jamesbond        --h=11 --w=7  --d=18 --max_cells=50000 --save_archive=./data/gesweep/Jamesbond_2.npy        &
python goexplore.py --seed=2 --env_id=Kangaroo         --h=14 --w=6  --d=16 --max_cells=50000 --save_archive=./data/gesweep/Kangaroo_2.npy         &
python goexplore.py --seed=2 --env_id=Krull            --h=7  --w=19 --d=13 --max_cells=50000 --save_archive=./data/gesweep/Krull_2.npy            &
python goexplore.py --seed=2 --env_id=KungFuMaster     --h=14 --w=15 --d=17 --max_cells=50000 --save_archive=./data/gesweep/KungFuMaster_2.npy     &
python goexplore.py --seed=2 --env_id=MontezumaRevenge --h=11 --w=11 --d=17 --max_cells=50000 --save_archive=./data/gesweep/MontezumaRevenge_2.npy &
python goexplore.py --seed=2 --env_id=MsPacman         --h=9  --w=5  --d=16 --max_cells=50000 --save_archive=./data/gesweep/MsPacman_2.npy         &
python goexplore.py --seed=2 --env_id=NameThisGame     --h=6  --w=6  --d=12 --max_cells=50000 --save_archive=./data/gesweep/NameThisGame_2.npy     &
python goexplore.py --seed=2 --env_id=Phoenix          --h=5  --w=9  --d=12 --max_cells=50000 --save_archive=./data/gesweep/Phoenix_2.npy          &
python goexplore.py --seed=2 --env_id=Pitfall          --h=19 --w=8  --d=4  --max_cells=50000 --save_archive=./data/gesweep/Pitfall_2.npy          &
python goexplore.py --seed=2 --env_id=Pong             --h=15 --w=6  --d=9  --max_cells=50000 --save_archive=./data/gesweep/Pong_2.npy             &
python goexplore.py --seed=2 --env_id=PrivateEye       --h=18 --w=9  --d=18 --max_cells=50000 --save_archive=./data/gesweep/PrivateEye_2.npy       &
python goexplore.py --seed=2 --env_id=Qbert            --h=4  --w=18 --d=12 --max_cells=50000 --save_archive=./data/gesweep/Qbert_2.npy            &
python goexplore.py --seed=2 --env_id=Riverraid        --h=17 --w=5  --d=5  --max_cells=50000 --save_archive=./data/gesweep/Riverraid_2.npy        &
wait
