python goexplore.py --env_id=Alien            --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Alien_0000.npy            &
python goexplore.py --env_id=Amidar           --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Amidar_0000.npy           &
python goexplore.py --env_id=Assault          --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Assault_0000.npy          &
python goexplore.py --env_id=Asterix          --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Asterix_0000.npy          &
python goexplore.py --env_id=Asteroids        --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Asteroids_0000.npy        &
python goexplore.py --env_id=Atlantis         --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Atlantis_0000.npy         &
python goexplore.py --env_id=BankHeist        --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/BankHeist_0000.npy        &
python goexplore.py --env_id=BattleZone       --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/BattleZone_0000.npy       &
python goexplore.py --env_id=BeamRider        --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/BeamRider_0000.npy        &
python goexplore.py --env_id=Berzerk          --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Berzerk_0000.npy          &
python goexplore.py --env_id=Bowling          --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Bowling_0000.npy          &
python goexplore.py --env_id=Boxing           --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Boxing_0000.npy           &
python goexplore.py --env_id=Breakout         --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Breakout_0000.npy         &
python goexplore.py --env_id=Centipede        --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Centipede_0000.npy        &
python goexplore.py --env_id=ChopperCommand   --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/ChopperCommand_0000.npy   &
python goexplore.py --env_id=CrazyClimber     --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/CrazyClimber_0000.npy     &
python goexplore.py --env_id=Defender         --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Defender_0000.npy         &
python goexplore.py --env_id=DemonAttack      --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/DemonAttack_0000.npy      &
python goexplore.py --env_id=DoubleDunk       --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/DoubleDunk_0000.npy       &
python goexplore.py --env_id=Enduro           --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Enduro_0000.npy           &
python goexplore.py --env_id=FishingDerby     --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/FishingDerby_0000.npy     &
python goexplore.py --env_id=Freeway          --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Freeway_0000.npy          &
python goexplore.py --env_id=Frostbite        --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Frostbite_0000.npy        &
python goexplore.py --env_id=Gopher           --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Gopher_0000.npy           &
python goexplore.py --env_id=Gravitar         --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Gravitar_0000.npy         &
python goexplore.py --env_id=Hero             --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Hero_0000.npy             &
python goexplore.py --env_id=IceHockey        --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/IceHockey_0000.npy        &
python goexplore.py --env_id=Jamesbond        --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Jamesbond_0000.npy        &
python goexplore.py --env_id=Kangaroo         --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Kangaroo_0000.npy         &
python goexplore.py --env_id=Krull            --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Krull_0000.npy            &
python goexplore.py --env_id=KungFuMaster     --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/KungFuMaster_0000.npy     &
python goexplore.py --env_id=MontezumaRevenge --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/MontezumaRevenge_0000.npy &
python goexplore.py --env_id=MsPacman         --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/MsPacman_0000.npy         &
python goexplore.py --env_id=NameThisGame     --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/NameThisGame_0000.npy     &
python goexplore.py --env_id=Phoenix          --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Phoenix_0000.npy          &
python goexplore.py --env_id=Pitfall          --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Pitfall_0000.npy          &
python goexplore.py --env_id=Pong             --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Pong_0000.npy             &
python goexplore.py --env_id=PrivateEye       --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/PrivateEye_0000.npy       &
python goexplore.py --env_id=Qbert            --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Qbert_0000.npy            &
python goexplore.py --env_id=Riverraid        --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Riverraid_0000.npy        &
wait

python goexplore.py --env_id=RoadRunner       --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/RoadRunner_0000.npy       &
python goexplore.py --env_id=Robotank         --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Robotank_0000.npy         &
python goexplore.py --env_id=Seaquest         --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Seaquest_0000.npy         &
python goexplore.py --env_id=Skiing           --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Skiing_0000.npy           &
python goexplore.py --env_id=Solaris          --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Solaris_0000.npy          &
python goexplore.py --env_id=SpaceInvaders    --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/SpaceInvaders_0000.npy    &
python goexplore.py --env_id=StarGunner       --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/StarGunner_0000.npy       &
python goexplore.py --env_id=Surround         --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Surround_0000.npy         &
python goexplore.py --env_id=Tennis           --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Tennis_0000.npy           &
python goexplore.py --env_id=TimePilot        --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/TimePilot_0000.npy        &
python goexplore.py --env_id=Tutankham        --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Tutankham_0000.npy        &
python goexplore.py --env_id=UpNDown          --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/UpNDown_0000.npy          &
python goexplore.py --env_id=Venture          --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Venture_0000.npy          &
python goexplore.py --env_id=VideoPinball     --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/VideoPinball_0000.npy     &
python goexplore.py --env_id=WizardOfWor      --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/WizardOfWor_0000.npy      &
python goexplore.py --env_id=YarsRevenge      --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/YarsRevenge_0000.npy      &
python goexplore.py --env_id=Zaxxon           --n_iters=2000 --max_cells=50000 --save_archive=./data/goexplore/Zaxxon_0000.npy           &
wait
