python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=0 --frame-stack=4  --obj=ext --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=0 --frame-stack=4  --obj=e3b --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=0 --frame-stack=8  --obj=ext --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=0 --frame-stack=8  --obj=e3b --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=0 --frame-stack=16 --obj=ext --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=0 --frame-stack=16 --obj=e3b --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=1 --frame-stack=4  --obj=ext --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=1 --frame-stack=4  --obj=e3b --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=1 --frame-stack=8  --obj=ext --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=1 --frame-stack=8  --obj=e3b --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=1 --frame-stack=16 --obj=ext --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=1 --frame-stack=16 --obj=e3b --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=2 --frame-stack=4  --obj=ext --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=2 --frame-stack=4  --obj=e3b --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=2 --frame-stack=8  --obj=ext --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=2 --frame-stack=8  --obj=e3b --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=2 --frame-stack=16 --obj=ext --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=2 --frame-stack=16 --obj=e3b --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=3 --frame-stack=4  --obj=ext --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=3 --frame-stack=4  --obj=e3b --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=3 --frame-stack=8  --obj=ext --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=3 --frame-stack=8  --obj=e3b --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=3 --frame-stack=16 --obj=ext --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=3 --frame-stack=16 --obj=e3b --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=4 --frame-stack=4  --obj=ext --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=4 --frame-stack=4  --obj=e3b --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=4 --frame-stack=8  --obj=ext --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=4 --frame-stack=8  --obj=e3b --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=4 --frame-stack=16 --obj=ext --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False
python ppo_atari.py --device=cuda --project=egb-atari --name={env_id}_{obj}_{seed} --seed=4 --frame-stack=16 --obj=e3b --env-id=MontezumaRevenge --total-steps=10e6 --anneal-lr=False