

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 2e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 2e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 2e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 4e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 4e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 4e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 8e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 8e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 8e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 16e0 --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 16e0 --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 16e0 --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8


python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 2e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 2e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 2e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 4e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 4e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 4e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 8e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 8e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 8e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 16e0 --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 16e0 --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 16e0 --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8


python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 2e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 2e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 2e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 4e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 4e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 4e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 8e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 8e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 8e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 16e0 --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 16e0 --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 16e0 --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8


python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 2e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 2e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 2e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 4e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 4e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 4e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 8e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 8e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 8e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 16e0 --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 16e0 --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 16e0 --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8


python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 2e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 2e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 2e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 4e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 4e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 4e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 8e0  --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 8e0  --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 8e0  --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 16e0 --obj ext     --distribution-mode easy --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 16e0 --obj nov     --distribution-mode easy --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8
python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 16e0 --obj ext+nov --distribution-mode easy --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{distribution_mode}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-8

