python ppo_procgen.py --num-levels 1e0 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 2e0 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 5e0 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 1e1 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 2e1 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 5e1 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 1e2 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 2e2 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 5e2 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 1e3 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track

python ppo_procgen.py --num-levels 1e0 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 2e0 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 5e0 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 1e1 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 2e1 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 5e1 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 1e2 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 2e2 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 5e2 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track
python ppo_procgen.py --num-levels 1e3 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 0 --device cuda --track

python ppo_procgen.py --num-levels 1e0 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 2e0 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 5e0 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 1e1 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 2e1 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 5e1 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 1e2 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 2e2 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 5e2 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 1e3 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track

python ppo_procgen.py --num-levels 1e0 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 2e0 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 5e0 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 1e1 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 2e1 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 5e1 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 1e2 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 2e2 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 5e2 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track
python ppo_procgen.py --num-levels 1e3 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 1 --device cuda --track

python ppo_procgen.py --num-levels 1e0 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 2e0 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 5e0 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 1e1 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 2e1 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 5e1 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 1e2 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 2e2 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 5e2 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 1e3 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track

python ppo_procgen.py --num-levels 1e0 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 2e0 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 5e0 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 1e1 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 2e1 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 5e1 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 1e2 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 2e2 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 5e2 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track
python ppo_procgen.py --num-levels 1e3 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 2 --device cuda --track

python ppo_procgen.py --num-levels 1e0 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 2e0 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 5e0 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 1e1 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 2e1 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 5e1 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 1e2 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 2e2 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 5e2 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 1e3 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track

python ppo_procgen.py --num-levels 1e0 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 2e0 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 5e0 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 1e1 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 2e1 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 5e1 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 1e2 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 2e2 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 5e2 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track
python ppo_procgen.py --num-levels 1e3 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 3 --device cuda --track

python ppo_procgen.py --num-levels 1e0 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 2e0 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 5e0 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 1e1 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 2e1 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 5e1 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 1e2 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 2e2 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 5e2 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 1e3 --obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track

python ppo_procgen.py --num-levels 1e0 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 2e0 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 5e0 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 1e1 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 2e1 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 5e1 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 1e2 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 2e2 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 5e2 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
python ppo_procgen.py --num-levels 1e3 --obj eps --gamma 0.999 --ent-coef 1e-2 --total-timesteps 25e6 --seed 4 --device cuda --track
