
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000000 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 00 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 0 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000001 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 01 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 1 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000002 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 02 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 2 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000003 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 03 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 3 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000004 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 04 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 4 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000005 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 05 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 5 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000006 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 06 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 6 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000007 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 07 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 7 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000008 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 08 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 8 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000009 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 09 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 9 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000010 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 10 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 0 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000011 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 11 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 1 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000012 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 12 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 2 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000013 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 13 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 3 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000014 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 14 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 4 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000015 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 15 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 5 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000016 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 16 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 6 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000017 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 17 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 7 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000018 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 18 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 8 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000019 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 19 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj ext --pre-seed 9 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}

python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000000 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 00 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 0 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000001 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 01 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 1 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000002 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 02 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 2 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000003 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 03 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 3 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000004 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 04 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 4 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000005 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 05 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 5 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000006 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 06 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 6 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000007 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 07 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 7 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000008 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 08 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 8 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000009 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 09 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 9 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000010 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 10 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 0 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000011 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 11 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 1 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000012 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 12 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 2 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000013 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 13 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 3 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000014 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 14 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 4 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000015 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 15 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 5 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000016 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 16 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 6 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000017 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 17 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 7 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000018 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 18 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 8 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000019 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 19 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name} --pre-obj cov --pre-seed 9 --load-agent data/{project}/residual_miner_000010_{pre_obj}_{pre_seed}

python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000000 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 00 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000001 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 01 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000002 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 02 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000003 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 03 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000004 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 04 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000005 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 05 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000006 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 06 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000007 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 07 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000008 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 08 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000009 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 09 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000010 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 10 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000011 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 11 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000012 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 12 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000013 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 13 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000014 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 14 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000015 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 15 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000016 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 16 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000017 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 17 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000018 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 18 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}
python ppo_procgen_lstm.py --warmup-critic-steps 2e6 --env-id miner --total-timesteps 5e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --start-level 1000019 --num-levels 1e0 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 19 --device cuda --track --name {lstm_type}_{env_id}_{pre_obj}_{obj}_{seed}_ft --project egb-lstm-5 --save-agent data/{project}/{name}




# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 5 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 6 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 7 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 8 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj ext --distribution-mode hard --lstm-type residual --actions ordinal --seed 9 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}

# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj cov --distribution-mode hard --lstm-type residual --actions ordinal --seed 0 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj cov --distribution-mode hard --lstm-type residual --actions ordinal --seed 1 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj cov --distribution-mode hard --lstm-type residual --actions ordinal --seed 2 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj cov --distribution-mode hard --lstm-type residual --actions ordinal --seed 3 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj cov --distribution-mode hard --lstm-type residual --actions ordinal --seed 4 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj cov --distribution-mode hard --lstm-type residual --actions ordinal --seed 5 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj cov --distribution-mode hard --lstm-type residual --actions ordinal --seed 6 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj cov --distribution-mode hard --lstm-type residual --actions ordinal --seed 7 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj cov --distribution-mode hard --lstm-type residual --actions ordinal --seed 8 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
# python ppo_procgen_lstm.py --env-id miner --total-timesteps 25e6 --learning-rate 5e-4 --idm-lr 5e-4 --num-envs 64 --num-steps 256 --num-minibatches 8 --update-epochs 3 --ent-coef 1e-2 --num-levels 1e1 --obj cov --distribution-mode hard --lstm-type residual --actions ordinal --seed 9 --device cuda --track --name {lstm_type}_{env_id}_{num_levels:06.0f}_{obj}_{seed} --project egb-lstm-5 --save-agent data/{project}/{name}
