python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=0 env-id=miner num-levels=1e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=0 env-id=miner num-levels=1e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=0 env-id=miner num-levels=1e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=0 env-id=miner num-levels=2e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=0 env-id=miner num-levels=2e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=0 env-id=miner num-levels=2e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=0 env-id=miner num-levels=4e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=0 env-id=miner num-levels=4e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=0 env-id=miner num-levels=4e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=0 env-id=miner num-levels=8e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=0 env-id=miner num-levels=8e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=0 env-id=miner num-levels=8e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=0 env-id=miner num-levels=16e0 obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=0 env-id=miner num-levels=16e0 obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=0 env-id=miner num-levels=16e0 obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=1 env-id=miner num-levels=1e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=1 env-id=miner num-levels=1e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=1 env-id=miner num-levels=1e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=1 env-id=miner num-levels=2e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=1 env-id=miner num-levels=2e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=1 env-id=miner num-levels=2e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=1 env-id=miner num-levels=4e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=1 env-id=miner num-levels=4e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=1 env-id=miner num-levels=4e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=1 env-id=miner num-levels=8e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=1 env-id=miner num-levels=8e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=1 env-id=miner num-levels=8e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=1 env-id=miner num-levels=16e0 obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=1 env-id=miner num-levels=16e0 obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=1 env-id=miner num-levels=16e0 obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=2 env-id=miner num-levels=1e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=2 env-id=miner num-levels=1e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=2 env-id=miner num-levels=1e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=2 env-id=miner num-levels=2e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=2 env-id=miner num-levels=2e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=2 env-id=miner num-levels=2e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=2 env-id=miner num-levels=4e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=2 env-id=miner num-levels=4e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=2 env-id=miner num-levels=4e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=2 env-id=miner num-levels=8e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=2 env-id=miner num-levels=8e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=2 env-id=miner num-levels=8e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=2 env-id=miner num-levels=16e0 obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=2 env-id=miner num-levels=16e0 obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=2 env-id=miner num-levels=16e0 obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=3 env-id=miner num-levels=1e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=3 env-id=miner num-levels=1e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=3 env-id=miner num-levels=1e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=3 env-id=miner num-levels=2e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=3 env-id=miner num-levels=2e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=3 env-id=miner num-levels=2e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=3 env-id=miner num-levels=4e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=3 env-id=miner num-levels=4e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=3 env-id=miner num-levels=4e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=3 env-id=miner num-levels=8e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=3 env-id=miner num-levels=8e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=3 env-id=miner num-levels=8e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=3 env-id=miner num-levels=16e0 obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=3 env-id=miner num-levels=16e0 obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=3 env-id=miner num-levels=16e0 obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=4 env-id=miner num-levels=1e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=4 env-id=miner num-levels=1e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=4 env-id=miner num-levels=1e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=4 env-id=miner num-levels=2e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=4 env-id=miner num-levels=2e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=4 env-id=miner num-levels=2e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=4 env-id=miner num-levels=4e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=4 env-id=miner num-levels=4e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=4 env-id=miner num-levels=4e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=4 env-id=miner num-levels=8e0  obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=4 env-id=miner num-levels=8e0  obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=4 env-id=miner num-levels=8e0  obj=ext+nov
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=4 env-id=miner num-levels=16e0 obj=ext    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=4 env-id=miner num-levels=16e0 obj=nov    
python ppo_procgen_lstm.py device=cuda track=True project=egb-lstm-8 name=simple seed=4 env-id=miner num-levels=16e0 obj=ext+nov