
python train.py --level 000 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 001 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 002 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 003 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 004 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 005 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 006 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 007 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 008 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 009 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 010 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 011 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 012 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 013 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 014 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 015 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 016 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 017 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 018 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 019 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 020 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 021 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 022 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 023 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 024 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 025 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 026 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 027 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 028 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 029 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 030 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 031 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 032 --train-obj ext --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}

python train.py --level 000 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 001 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 002 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 003 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 004 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 005 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 006 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 007 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 008 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 009 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 010 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 011 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 012 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 013 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 014 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 015 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 016 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 017 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 018 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 019 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 020 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 021 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 022 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 023 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 024 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 025 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 026 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 027 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 028 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 029 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 030 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 031 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 032 --train-obj int --gamma 0.999 --ent-coef 1e-2 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}

python train.py --level 000 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 001 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 002 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 003 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 004 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 005 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 006 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 007 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 008 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 009 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 010 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 011 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 012 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 013 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 014 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 015 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 016 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 017 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 018 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 019 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 020 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 021 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 022 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 023 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 024 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 025 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 026 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 027 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 028 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 029 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 030 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 031 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 032 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
