python train.py --level 00000 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00001 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00002 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00003 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00004 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00005 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00006 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00007 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00008 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00009 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00010 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00011 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00012 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00013 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00014 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00015 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00016 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00017 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00018 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00019 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00020 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00021 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00022 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00023 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00024 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00025 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00026 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00027 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00028 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00029 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00030 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00031 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00032 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00033 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00034 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00035 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00036 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00037 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00038 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00039 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00040 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00041 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00042 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00043 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00044 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00045 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00046 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00047 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00048 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00049 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00050 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00051 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00052 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00053 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00054 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00055 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00056 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00057 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00058 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00059 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00060 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00061 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00062 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00063 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00064 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00065 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00066 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00067 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00068 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00069 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00070 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00071 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00072 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00073 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00074 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00075 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00076 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00077 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00078 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00079 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00080 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00081 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00082 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00083 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00084 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00085 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00086 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00087 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00088 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00089 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00090 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00091 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00092 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00093 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00094 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00095 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00096 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00097 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00098 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00099 --train-obj ext --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00000 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00001 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00002 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00003 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00004 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00005 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00006 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00007 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00008 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00009 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00010 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00011 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00012 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00013 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00014 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00015 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00016 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00017 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00018 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00019 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00020 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00021 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00022 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00023 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00024 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00025 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00026 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00027 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00028 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00029 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00030 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00031 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00032 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00033 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00034 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00035 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00036 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00037 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00038 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00039 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00040 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00041 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00042 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00043 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00044 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00045 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00046 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00047 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00048 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00049 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00050 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00051 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00052 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00053 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00054 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00055 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00056 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00057 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00058 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00059 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00060 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00061 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00062 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00063 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00064 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00065 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00066 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00067 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00068 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00069 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00070 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00071 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00072 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00073 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00074 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00075 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00076 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00077 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00078 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00079 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00080 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00081 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00082 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00083 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00084 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00085 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00086 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00087 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00088 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00089 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00090 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00091 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00092 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00093 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00094 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00095 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00096 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00097 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00098 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00099 --train-obj int --gamma 0.999 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00000 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00001 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00002 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00003 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00004 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00005 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00006 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00007 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00008 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00009 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00010 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00011 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00012 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00013 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00014 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00015 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00016 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00017 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00018 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00019 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00020 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00021 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00022 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00023 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00024 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00025 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00026 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00027 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00028 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00029 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00030 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00031 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00032 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00033 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00034 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00035 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00036 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00037 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00038 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00039 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00040 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00041 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00042 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00043 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00044 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00045 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00046 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00047 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00048 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00049 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00050 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00051 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00052 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00053 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00054 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00055 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00056 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00057 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00058 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00059 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00060 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00061 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00062 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00063 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00064 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00065 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00066 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00067 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00068 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00069 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00070 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00071 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00072 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00073 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00074 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00075 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00076 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00077 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00078 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00079 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00080 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00081 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00082 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00083 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00084 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00085 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00086 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00087 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00088 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00089 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00090 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00091 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00092 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00093 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00094 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00095 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00096 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00097 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00098 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
python train.py --level 00099 --train-obj eps --gamma 0.900 --ent-coef 1e-1 --total-timesteps 4e7 --device cuda --track --project exploration-distillation-data --name {env}_{level:05d}_{train_obj}
